// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8XCa8kpM25BgC6qbulyei9pFo39-RQI',
    appId: '1:1029657831685:web:f0ac3b33936c0643346f6c',
    messagingSenderId: '1029657831685',
    projectId: 'opso-dev-3f5d1',
    authDomain: 'opso-dev-3f5d1.firebaseapp.com',
    storageBucket: 'opso-dev-3f5d1.firebasestorage.app',
    measurementId: 'G-64S6E7XMF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXeCiQkrrsUycUA1zpHCLsduKdCvrB068',
    appId: '1:1029657831685:android:83328862ec4c79ec346f6c',
    messagingSenderId: '1029657831685',
    projectId: 'opso-dev-3f5d1',
    storageBucket: 'opso-dev-3f5d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzYyQHP5hr-_NriILxFgQo2X9wKQBI84U',
    appId: '1:1029657831685:ios:18a2fc403d7532aa346f6c',
    messagingSenderId: '1029657831685',
    projectId: 'opso-dev-3f5d1',
    storageBucket: 'opso-dev-3f5d1.firebasestorage.app',
    iosBundleId: 'com.example.opso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzYyQHP5hr-_NriILxFgQo2X9wKQBI84U',
    appId: '1:1029657831685:ios:18a2fc403d7532aa346f6c',
    messagingSenderId: '1029657831685',
    projectId: 'opso-dev-3f5d1',
    storageBucket: 'opso-dev-3f5d1.firebasestorage.app',
    iosBundleId: 'com.example.opso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK8XCa8kpM25BgC6qbulyei9pFo39-RQI',
    appId: '1:1029657831685:web:e442d0677569f042346f6c',
    messagingSenderId: '1029657831685',
    projectId: 'opso-dev-3f5d1',
    authDomain: 'opso-dev-3f5d1.firebaseapp.com',
    storageBucket: 'opso-dev-3f5d1.firebasestorage.app',
    measurementId: 'G-XFWGMELLSS',
  );

}